# Generated by Django 4.2.11 on 2024-07-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('rejected', 'Rejected'), ('disabled', 'Disabled'), ('published', 'Published'), ('in_review', 'IN Review')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productsreviews',
            name='rating',
            field=models.ImageField(choices=[(2, '★★✩✩✩'), (3, '★★★✩✩'), (4, '★★★★✩'), (1, '★✩✩✩✩'), (5, '★★★★★')], default=None, upload_to=''),
        ),
    ]
