# Generated by Django 4.2.11 on 2024-07-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_product_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImage',
            new_name='ExtraImages',
        ),
        migrations.AlterModelOptions(
            name='extraimages',
            options={'verbose_name_plural': 'ExtraImages'},
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('published', 'Published'), ('in_review', 'IN Review'), ('disabled', 'Disabled'), ('draft', 'Draft'), ('rejected', 'Rejected')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productsreviews',
            name='rating',
            field=models.ImageField(choices=[(1, '★✩✩✩✩'), (5, '★★★★★'), (4, '★★★★✩'), (2, '★★✩✩✩'), (3, '★★★✩✩')], default=None, upload_to=''),
        ),
    ]
