# Generated by Django 4.2.11 on 2024-07-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_productimage_extraimages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('in_review', 'IN Review'), ('published', 'Published'), ('rejected', 'Rejected'), ('disabled', 'Disabled'), ('draft', 'Draft')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productsreviews',
            name='rating',
            field=models.ImageField(choices=[(5, '★★★★★'), (1, '★✩✩✩✩'), (3, '★★★✩✩'), (4, '★★★★✩'), (2, '★★✩✩✩')], default=None, upload_to=''),
        ),
    ]
