# Generated by Django 4.2.11 on 2024-07-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('published', 'Published'), ('rejected', 'Rejected'), ('draft', 'Draft'), ('in_review', 'IN Review')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productsreviews',
            name='rating',
            field=models.ImageField(choices=[(1, '★✩✩✩✩'), (4, '★★★★✩'), (5, '★★★★★'), (2, '★★✩✩✩'), (3, '★★★✩✩')], default=None, upload_to=''),
        ),
    ]
