"""
Django settings for my_ecommerce_site project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qpsmkic)uapj$*@7e2n$uh*d)x%f-a0u&q60eis(m7!hty0z3n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'products',
    'accounts',
    'blog',
    'tinymce',
    'django_otp',
    'django_otp.plugins.otp_email',


]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'my_ecommerce_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # Use os.path.join to create the directory path
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'products.context_processors.cart_context',  # Add cart_context
                'products.context_processors.categories_processor',  # Add categories_processor

            ],
        },
    },
]


WSGI_APPLICATION = 'my_ecommerce_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        # Ensure that 'NAME' is correctly concatenated as a string path
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]



# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']  # Project-wide static files
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Directory for collectstatic

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# URL to access media files
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    "site_title": "My Admin",
    "site_header": "My Admin Site",
    "site_brand": "My Admin",
    "site_logo": "path/to/logo.png",  # Update with the path to your logo if you have one
    "welcome_sign": "Welcome to My Admin Site",

    # Model ordering and grouping
    "order_with_respect_to": [
        "products.Address",
        "products.BillingAddress",
        "products.ShippingAddress",
        "---------",
        "products.Cart",
        "products.CartItem",
        "---------",
        "products.Order",
        "products.OrderItem",
        "---------",
        "products.MainCategory",
        "products.SubCategory",
        "products.Product",
        "products.Inventory",
        "---------",
        "products.SiteSettings",
        "products.ProductsReviews",
        "products.Wishlist",
    ],

    # Application ordering (optional)
    "apps_order": [
        "accounts",
        "products",
    ],

    # Theme settings
    "theme": "simplex",  # Apply the Simplex theme
}

AUTH_USER_MODEL = 'accounts.User'  # Correct reference



TINYMCE_DEFAULT_CONFIG = {
    'height': 360,
    'width': 800,
}



# settings.py

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'prathameshshigwan52@gmail.com'
EMAIL_HOST_PASSWORD = 'mpkg yhyn czae qlel'


# settings.py
RAZORPAY_KEY_ID = 'rzp_test_KNDTUWOZLejvQp'
RAZORPAY_KEY_SECRET = 'BlKrxZkEyxkyC0SWUjC2ZNIV'


